# Overwritten on deploy from alphagov-deployment

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 790a3e02bb7b8129a202cae0e9cdfd14d97290924dfa26a60000f94ba4c81146a4f63f082f7c5ffa91cfaae49148f1ab4e6759c734d24c46bc43ed5692e5a93f

test:
  secret_key_base: ab07abacece132170f4beaff1d9d501837ad776235da9aef2abfc5ed0b33e26ecd43c0fc0b96ce3ea604dce6c7fca0ab9a0bb7105bd22cc26a74d65a8f4daf69
